version: '3.7'

services:
 
  db-universidade:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:

